create a elpaas-php-apache2

diff --git a/bin/elpaasochecker b/bin/elpaasochecker
--- a/bin/elpaasochecker
+++ b/bin/elpaasochecker
@@ -1,11 +1,22 @@
-notice "Check __APP_NAME__ env var is set"
+
+error() {
+  echo
+  echo -n " !     ERROR: "
+  echo "$*" | indent
+  echo
+  exit 1
+}
+notice_inline() {
+  echo "NOTICE: $*" | indent
+}
+echo notice_inline "Check __APP_NAME__ env var is set"
 
 if [ -z "$__APP_NAME__" ]; then
     error "__APP_NAME__ env var should be set"
     exit 1
 fi
 APP_DIR_TEMP=${__APP_NAME__}_APP_DIR
-notice "Check ${APP_DIR_TEMP} env var is set"
+notice_inline "Check ${APP_DIR_TEMP} env var is set"
 if [[ -z "${!APP_DIR_TEMP+x}" ]]; then
     error "${APP_DIR_TEMP} env var should be set"
     exit 1
